# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30dcb0a966ab99dc184ee7bf1991880e6a9a3a09b6c7d6514848596c70640052b283c5e2639defcf23510da10055ddf5cd264431b6fea7d5f9c1175c7997f3ab

test:
  secret_key_base: 41dedb6ea6c2b1ba6a24b524a0365846b5251d9276204022b38f5d4a10c3409a92f5fa4942b379592bd39f0f8b43ca61f6282193fae08d0dd26b924830af4cbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
